### ISSUE TITLE
.eslintrc is deprecated now.

### ISSUE THREAD

**Issue by isdh** [joakim-eriksson/nb-eslint#30] opened 2019-06-13 07:04 UTC
.eslintrc is deprecated now.
https://eslint.org/docs/user-guide/configuring#configuration-file-formats

Could you support .eslintrc.json or .eslintrc.yaml file ?
Or,  I feel so lucky if I could choose .eslintrc file extension exclude .eslintrc.

**Comment by Chris2011** [comment] 2019-06-13 07:22
We should support all supported filetypes. Deprecated or not, because it is still possible to use it. But yes the priority order is clear.

**Comment by Rade0nFighter** [comment] 2020-03-05 02:37
Has there been any development on this? Also are there any issues with nb 11?

**Comment by Chris2011** [comment] 2020-03-05 07:49
> Has there been any development on this?

I didn't find time to help here. Will check it out later.

> Also are there any issues with nb 11?

Try it out :)

**Comment by Rade0nFighter** [comment] 2020-03-06 12:52
@Chris2011  No worries! Have been testing in NB11 and have noticed the following:

- Plugin still only seems to pick up the old .eslintrc file name (can tell as it shows the purple eslint icon for the file)
- Plugin doesn't seem to have any effect after renaming file, not sure if the built in inspections are the cause, but turning them off doesn't make eslint warnings appear. Perhaps I'm missing something obvious?

<img width="835" alt="Screenshot 2020-03-06 at 12 51 54" src="https://user-images.githubusercontent.com/13593745/76085096-46ca5b80-5fa9-11ea-843c-4d21d26df512.png">

**Comment by Chris2011** [comment] 2020-03-06 13:02
Everything is just registered for this file: https://github.com/joakim-eriksson/nb-eslint/search?q=eslintrc&unscoped_q=eslintrc nothing more. We need to change the mimresolver for that to catch everything that is `.eslintrc.*` smth like that: https://github.com/ksfreitas/gwt4nb/blob/master/src/com/nanosn/netbeans/gwtxml/GwtXmlResolver.xml

**Comment by Rade0nFighter** [comment] 2020-03-07 00:22
@Chris2011 Awesome thank you for the reply, I will if I can have a look at the mimeresolver but I'm not java expert so fear I may struggle!

Okay so after more playing around I have concluded the following (TLDR it works save for the purple icon which is no biggie):

- It does indeed work after restarting netbeans having entered the configuration above 
- When pointing the configuration to .eslintrc.json in the Conf: option, the appropriate rules are used to provide the red highlighting
- One needs to edit and save the file for highlighting to appear, it doesn't appear whilst typing/hitting return for a nl
- Occasionally netbeans requires a restart to pickup changes in the .eslintrc.json file (assume this is a nb issue)
- Line numbers don't show the error annotation, but the lne will be highlighted, and if you hover over where the icon should be you get the message (again maybe a nb thing since updating major versions):
<img width="199" alt="Screenshot 2020-03-07 at 01 00 14" src="https://user-images.githubusercontent.com/13593745/76133241-34830880-600f-11ea-8bf6-81abf3ca6a97.png">
 

All in all works as expected and the recently added additional config options solve most problems :)

Now the "standard" ruleset seems to have stopped working randomly ("eslint:all" okay, and is "standard via command line), which feels like a nb issue again, I will share a fix if I find it but if anyone has any ideas I'd be grateful, have tried clearing caches etc...

**Comment by Chris2011** [comment] 2020-10-06 22:56
I created a PR #32, it will now look hierarchical for the config files that are mentioned in the official documentation. Using package.json is out of scope of this PR. I will add it later. So the PR can stay open, until I added the package.json.

**Comment by Chris2011** [comment] 2020-10-07 18:36
PR will now use the eslint internal logic to get the correct eslint file. If there is no eslint file, it will take the eslintConfig object, if there is one, in the package.json file. Now we have a checkbox to choose a project based config file over a custom one.

**Comment by Chris2011** [comment] 2020-10-08 14:04
So after the PR was merged, thx to @joakim-eriksson we can close this issue and wait for version 1.3.0. Please create one.

**Closed as completed by Chris2011** 2020-10-08 14:04 UTC

**Comment by Chris2011** [comment] 2020-10-08 19:17
And please build the plugin for the smallest version of Apache NetBeans so version 9. That everyone has smth of it :)
